modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="zanyelements"
version="0.1.0"
displayName="ZanyElements"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Shadowdragon, MCreator"
description='''
Join the Discord!: https://discord.gg/YYM3NYssSJ
'''

[[dependencies.zanyelements]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




